### ISSUE TITLE
Exported Share Link/QRCode doesn't have same JSON config as source

### ISSUE THREAD

**Issue by amirsaam** [LorenEteval/Furious#8] opened 2023-09-05 08:22 UTC
As said in the title, this is a big issue, hope to see a way to fix it.
You can test this via adding your `vless` share link to [vless to fragment convertor](https://rrouzbeh.github.io/ray2fragment/) and changing the json in the app then exporting via share link or qr code.

**Comment by LorenEteval** [comment] 2023-09-05 11:03
Does this fragment convertor even generate corrent Xray-core configuration? I cannot connect using generated json.

**Comment by amirsaam** [comment] 2023-09-05 11:19
Yes it does and works perfectly. I'm saying again you need a vless share link but it doesn't matter if it does work or not for you. Furious is not sharing correct JSON config in the output for QR and Share link.

**Comment by LorenEteval** [comment] 2023-09-05 11:34
It seems not a standard convertor and there's no plan to research this. I'll close this issue.

**Closed by LorenEteval** 2023-09-05 11:34 UTC
Labels: invalid, question

**Comment by amirsaam** [comment] 2023-09-05 11:45
> It seems not a standard convertor and there's no plan to research this. I'll close this issue.

this is not a valid response. 
it's not about that convertor or any other ones. when you make changes in json config, the share link and qr code on Furious do not have your changes in it when you share it. I cannot understand what is wrong with asking for fixing it?

**Comment by LorenEteval** [comment] 2023-09-05 12:48
Did you save your changes via `command + s`? If so, is the share success or not?

Please give me at least one VLESS link(replace sensitive information in it) which is able to describe/re-produce your problem, otherwise the issue is no help for me.

**Comment by amirsaam** [comment] 2023-09-05 14:26
import this config as json to Furious
```
{
    "dns": {
        "hosts": {
            "domain:googleapis.cn": "googleapis.com"
        },
        "servers": [
            "1.1.1.1"
        ]
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 10808,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true,
                "userLevel": 8
            },
            "sniffing": {
                "destOverride": [
                    "http",
                    "tls"
                ],
                "enabled": true
            },
            "tag": "socks"
        },
        {
            "listen": "127.0.0.1",
            "port": 10809,
            "protocol": "http",
            "settings": {
                "userLevel": 8
            },
            "tag": "http"
        }
    ],
    "log": {
        "loglevel": "warning"
    },
    "outbounds": [
        {
            "mux": {
                "concurrency": 8,
                "enabled": false
            },
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "v2ray.example.com",
                        "port": 443,
                        "users": [
                            {
                                "encryption": null,
                                "flow": "",
                                "id": "USERID",
                                "level": 8,
                                "security": "auto"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": false,
                    "alpn": [
                        "http/1.1"
                    ],
                    "fingerprint": "chrome",
                    "publicKey": "",
                    "serverName": "v2ray.example.com",
                    "shortId": "",
                    "show": false,
                    "spiderX": ""
                },
                "wsSettings": {
                    "headers": {
                        "Host": "v2ray.example.com"
                    },
                    "path": "/f5322046"
                }
            },
            "proxySettings": {
                "tag": "fragment",
                "transportLayer": true
            },
            "tag": "proxy"
        },
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        },
        {
            "protocol": "freedom",
            "tag": "fragment",
            "domainStrategy": "UseIP",
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            },
            "settings": {
                "fragment": {
                    "packets": "tlshello",
                    "length": "100-200",
                    "interval": "10-20"
                }
            },
            "streamSettings": {
                "sockopt": {
                    "tcpNoDelay": true,
                    "domainStrategy": "UseIP"
                }
            }
        },
        {
            "protocol": "blackhole",
            "settings": {
                "response": {
                    "type": "http"
                }
            },
            "tag": "block"
        }
    ],
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "ip": [
                    "1.1.1.1"
                ],
                "outboundTag": "proxy",
                "port": "53",
                "type": "field"
            }
        ]
    }
}
```
It would give you a config in Furious. Now share link it and re-import it to Furious or Scan QR Code it in an app that let's you edit JSON config like NapsternetV.
What you'll get is not the same JSON config you have imported to Furious.

P.S.: This JSON is the same JSON I use for my own VPN and does works perfectly (of course w/o the real server address)

**Comment by LorenEteval** [comment] 2023-09-06 04:30
> import this config as json to Furious
> 
> ```
> {
>     "dns": {
>         "hosts": {
>             "domain:googleapis.cn": "googleapis.com"
>         },
>         "servers": [
>             "1.1.1.1"
>         ]
>     },
>     "inbounds": [
>         {
>             "listen": "127.0.0.1",
>             "port": 10808,
>             "protocol": "socks",
>             "settings": {
>                 "auth": "noauth",
>                 "udp": true,
>                 "userLevel": 8
>             },
>             "sniffing": {
>                 "destOverride": [
>                     "http",
>                     "tls"
>                 ],
>                 "enabled": true
>             },
>             "tag": "socks"
>         },
>         {
>             "listen": "127.0.0.1",
>             "port": 10809,
>             "protocol": "http",
>             "settings": {
>                 "userLevel": 8
>             },
>             "tag": "http"
>         }
>     ],
>     "log": {
>         "loglevel": "warning"
>     },
>     "outbounds": [
>         {
>             "mux": {
>                 "concurrency": 8,
>                 "enabled": false
>             },
>             "protocol": "vless",
>             "settings": {
>                 "vnext": [
>                     {
>                         "address": "v2ray.example.com",
>                         "port": 443,
>                         "users": [
>                             {
>                                 "encryption": null,
>                                 "flow": "",
>                                 "id": "USERID",
>                                 "level": 8,
>                                 "security": "auto"
>                             }
>                         ]
>                     }
>                 ]
>             },
>             "streamSettings": {
>                 "network": "ws",
>                 "security": "tls",
>                 "tlsSettings": {
>                     "allowInsecure": false,
>                     "alpn": [
>                         "http/1.1"
>                     ],
>                     "fingerprint": "chrome",
>                     "publicKey": "",
>                     "serverName": "v2ray.example.com",
>                     "shortId": "",
>                     "show": false,
>                     "spiderX": ""
>                 },
>                 "wsSettings": {
>                     "headers": {
>                         "Host": "v2ray.example.com"
>                     },
>                     "path": "/f5322046"
>                 }
>             },
>             "proxySettings": {
>                 "tag": "fragment",
>                 "transportLayer": true
>             },
>             "tag": "proxy"
>         },
>         {
>             "protocol": "freedom",
>             "settings": {},
>             "tag": "direct"
>         },
>         {
>             "protocol": "freedom",
>             "tag": "fragment",
>             "domainStrategy": "UseIP",
>             "sniffing": {
>                 "enabled": true,
>                 "destOverride": [
>                     "http",
>                     "tls"
>                 ]
>             },
>             "settings": {
>                 "fragment": {
>                     "packets": "tlshello",
>                     "length": "100-200",
>                     "interval": "10-20"
>                 }
>             },
>             "streamSettings": {
>                 "sockopt": {
>                     "tcpNoDelay": true,
>                     "domainStrategy": "UseIP"
>                 }
>             }
>         },
>         {
>             "protocol": "blackhole",
>             "settings": {
>                 "response": {
>                     "type": "http"
>                 }
>             },
>             "tag": "block"
>         }
>     ],
>     "routing": {
>         "domainStrategy": "IPIfNonMatch",
>         "rules": [
>             {
>                 "ip": [
>                     "1.1.1.1"
>                 ],
>                 "outboundTag": "proxy",
>                 "port": "53",
>                 "type": "field"
>             }
>         ]
>     }
> }
> ```
> 
> It would give you a config in Furious. Now share link it and re-import it to Furious or Scan QR Code it in an app that let's you edit JSON config like NapsternetV. What you'll get is not the same JSON config you have imported to Furious.
> 
> P.S.: This JSON is the same JSON I use for my own VPN and does works perfectly (of course w/o the real server address)

Conversion from share link to the actual client json is completely implementation defined. The only thing that each different implementation tries to ensure is that the generated share link is in **correct** format, and has as many **correct** client settings as possible based on the **VLESS/VMess share standard**. The standard just covers any key fields that's essential to define the protocol/connection.

I'm not sure if this answers your question?

**Comment by amirsaam** [comment] 2023-09-06 09:26
Do you understand that if as an admin of vpn server, you change things in the json config you expect when you share it to users it needs to be same thing?
So, if I change the JSON and you say the share link won't support it, disable it and don't lemme share it via share link but I do expect to QR code work as intended. Does it make sense for you this way?

**Comment by LorenEteval** [comment] 2023-09-06 10:22
You can use whatever you want to use based on your understand. Please, stop talking nonsense.

This conversation is over. If you continue I'll lock this issue.
