### ISSUE TITLE
DNS issue

### ISSUE THREAD

**Issue by khashayarxy** [LorenEteval/Furious#53] opened 2023-12-08 00:33 UTC
I recently have noticed that Furious doesn't open some apps or images and I think it's the lack of a DNS system built-in.

For example Microsoft Store doesn't work properly or XBOX app doesn't load images and this kinda stuff.

When I used a custom dns on my network settings, the issue was gone. I even checked NekoRay and didn't found the same issue.

Please kindly look into this. Thanks!

**Comment by khashayarxy** [comment] 2023-12-30 22:46
Hello there,
I haven't seen this problem with Nekoray neither with Proxy mode or Tun mode.

I just noticed that I haven't enabled VPN mode on Furious and I've been using Proxy mode.

so I enabled VPN mode but It seems not working even after closing and opening the app again.

"Tun2Socks: Core terminated unexpectedly"

**Comment by khashayarxy** [comment] 2023-12-30 23:12
I downloaded wintun and the error is fixed.

VPN mode is enabled and I still have the same issues with Microsoft Store and XBOX app.

Here's the Furious VPN mode:

![Screenshot 2023-12-31 023134](https://github.com/LorenEteval/Furious/assets/42047526/ed46896b-da6a-44b7-b388-660c6eec4b86)
![Screenshot 2023-12-31 023428](https://github.com/LorenEteval/Furious/assets/42047526/5b0f5052-0316-4b71-b879-d05668136562)

**Comment by khashayarxy** [comment] 2023-12-30 23:16
This is Nekoray with both Tun mode and Proxy mode (with the same server as used on Furious).
 
![Screenshot 2023-12-31 023616](https://github.com/LorenEteval/Furious/assets/42047526/84ff2b2a-a43d-4adb-b1c5-236a1083eb57)
![Screenshot 2023-12-31 023552](https://github.com/LorenEteval/Furious/assets/42047526/6bf95924-47c0-430a-b500-b7b7875d8fa8)

**Comment by LorenEteval** [comment] 2024-01-02 16:53
This seems not related to DNS. A duplicate of [this](https://github.com/2dust/v2rayN/issues/1083).

**Closed by LorenEteval** 2024-01-02 16:53 UTC

**Comment by khashayarxy** [comment] 2024-01-09 10:38
I didn't understand. this issue will be fixed or users have to run some code?

**Comment by LorenEteval** [comment] 2024-01-11 06:14
> I didn't understand. this issue will be fixed or users have to run some code?

There is nothing to **fix**. A new feature `Bypass UWP Application Loopback Proxy Restrictions` entry will be added.
